- hosts: client
  tasks:
    - copy:
        src: /jdk-8u171-linux-x64.rpm
        dest: /root
    - copy:
        src: /hadoop-1.2.1-1.x86_64.rpm
        dest: /root
    - shell: "rpm -i /root/jdk-8u171-linux-x64.rpm"
    - shell: "rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force"

    - copy:
        src: /root/MRCLUSTER/client/hdfs-site.xml
        dest: /etc/hadoop
    - copy:
        src: /root/MRCLUSTER/client/core-site.xml
        dest: /etc/hadoop
